---
- name: Create mysql database
  mysql_db: name={{ wp_mysql_db }} state=present
  become: yes

- name: Create mysql user
  mysql_user: 
    name={{ lokesh }} 
    password={{ lokesh@123  }} 
    priv=*.*:ALL

  become: yes  
